### ISSUE TITLE
If some output parameters starts with the same name, no OK in the Testflow is possible

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#102]
![outpara](https://user-images.githubusercontent.com/75318923/127308533-31a0fbc6-b27c-4ae5-94a4-2529d6a311d6.jpg)

Traceback (most recent call last):
  File "c:\users\appslab\ate\semi-ate\ATE\spyder\widgets\actions_on\program\TestProgramWizard.py", line 1143, in _save_configuration
    definition = self._custom_parameter_handler.build_defintion()
  File "c:\users\appslab\ate\semi-ate\ATE\spyder\widgets\actions_on\program\Parameters\TestProgram.py", line 156, in build_defintion
    definition.append(test.serialize_definition())
  File "c:\users\appslab\ate\semi-ate\ATE\spyder\widgets\actions_on\program\Parameters\TestParameters.py", line 61, in serialize_definition
    struct['output_parameters'] = self.serialize_output_parameters()
  File "c:\users\appslab\ate\semi-ate\ATE\spyder\widgets\actions_on\program\Parameters\TestParameters.py", line 97, in serialize_output_parameters
    'result': Result.Fail() if int(bin_parameter.bin_number) not in range(1, 10) else Result.Pass(),
ValueError: invalid literal for int() with base 10: ''
2021-07-28 12:13:07,663 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered

**Comment by Zlin526F** [comment]
done
