### ISSUE TITLE
Widget TestWizard no longer running 

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#107]
TestWizard needs qtawesome=0.7.2 but the latest spyder needs qtawesome >=1.0.2,
so the TestWizard get an error:

Traceback (most recent call last):
  File "C:\Users\.....\maxiconda\envs\_spyder_\lib\site-packages\ATE\spyder\widgets\actions_on\utils\ExceptionHandler.py", line 21, in handle_excpetions
    call_back_function()
  File "C:\Users\.....\maxiconda\envs\_spyder_\lib\site-packages\ATE\spyder\widgets\actions_on\tests\TestItems\TestItemChild.py", line 34, in <lambda>
    lambda: edit_test_dialog(self.project_info, test_content),
  File "C:\Users\.....\maxiconda\envs\_spyder_\lib\site-packages\ATE\spyder\widgets\actions_on\tests\TestWizard.py", line 1788, in edit_test_dialog
    edit = TestWizard(project_info, test_content=test_content, read_only=True)
  File "C:\Users\......\maxiconda\envs\_spyder_\lib\site-packages\ATE\spyder\widgets\actions_on\tests\TestWizard.py", line 172, in __init__
    self.inputParameterFormat.setIcon(qta.icon('mdi.settings', color='orange'))
  File "C:\Users\..\maxiconda\envs\_spyder_\lib\site-packages\qtawesome\__init__.py", line 173, in icon
    return _instance().icon(*names, **kwargs)
  File "C:\Users\......\maxiconda\envs\_spyder_\lib\site-packages\qtawesome\iconic_font.py", line 304, in icon
    parsed_options.append(self._parse_options(specific_options,
  File "C:\Users\.......\maxiconda\envs\_spyder_\lib\site-packages\qtawesome\iconic_font.py", line 354, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "C:\Users\......\maxiconda\envs\_spyder_\lib\site-packages\qtawesome\iconic_font.py", line 385, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid icon name "settings" in font "mdi"

**Comment by Zlin526F** [comment]
mdi.settings and mdi.settings-outline isn't available in qtawesome >= 1.02
