### ISSUE TITLE
OSError: [Errno 24] inotify instance limit reached

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/Semi-ATE#16]
Traceback (most recent call last):
  File "/home/nerohmot/Desktop/Repos/Semi-ATE/Semi-ATE/ATE/spyder/widgets/actions_on/model/TreeModel.py", line 93, in apply_toolbar_change
    self._update_tests()
  File "/home/nerohmot/Desktop/Repos/Semi-ATE/Semi-ATE/ATE/spyder/widgets/actions_on/model/TreeModel.py", line 263, in _update_tests
    self.tests_section.update()
  File "/home/nerohmot/Desktop/Repos/Semi-ATE/Semi-ATE/ATE/spyder/widgets/actions_on/tests/TestItem.py", line 63, in update
    super().update()
  File "/home/nerohmot/Desktop/Repos/Semi-ATE/Semi-ATE/ATE/spyder/widgets/actions_on/model/BaseItem.py", line 45, in update
    self._append_children()
  File "/home/nerohmot/Desktop/Repos/Semi-ATE/Semi-ATE/ATE/spyder/widgets/actions_on/tests/TestItem.py", line 34, in _append_children
    self.observer.start_observer()
  File "/home/nerohmot/Desktop/Repos/Semi-ATE/Semi-ATE/ATE/spyder/widgets/actions_on/utils/ObserverBase.py", line 102, in start_observer
    self.observer.start()
  File "/home/nerohmot/conda-envs/spyder/lib/python3.8/site-packages/watchdog/observers/api.py", line 260, in start
    emitter.start()
  File "/home/nerohmot/conda-envs/spyder/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/home/nerohmot/conda-envs/spyder/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/nerohmot/conda-envs/spyder/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/nerohmot/conda-envs/spyder/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 189, in __init__
    Inotify._raise_error()
  File "/home/nerohmot/conda-envs/spyder/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 426, in _raise_error
    raise OSError(errno.EMFILE, "inotify instance limit reached")
OSError: [Errno 24] inotify instance limit reached

**Comment by nerohmot** [comment]
where do we implement such a fix, in `Semi-ATE` ? 
maybe a post-install script that runs ... but /etc/sysctl.conf ... one needs root privileges ....
