### ISSUE TITLE
Exception occurs when add a test to another group and then delete this test in the group

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#313]
an exception occurs when i add a test to another group and then delete this test in the group:

![image](https://user-images.githubusercontent.com/75318923/217294465-c6b689cb-12d6-4b06-a16b-625d8bb33940.png)

![image](https://user-images.githubusercontent.com/75318923/217295278-a22d3ed3-40bb-492c-a2bd-0ac95ccf99ca.png)

and then try to edit the file again in the first group:
![image](https://user-images.githubusercontent.com/75318923/217295611-bc7b4896-bc4b-44b4-ad96-791754fb92ba.png)

Traceback (most recent call last):
  File "semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\TestItems\TestItemChild.py", line 32, in edit_item
    test_content = self._get_test_content()
  File "semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\TestItems\TestItemChild.py", line 38, in _get_test_content
    return self.project_info.get_test_table_content(self.text(), self.project_info.active_hardware, self.project_info.active_base)
  File "semi-ate\src\ate_spyder\ate_spyder\widgets\navigation.py", line 689, in get_test_table_content
    table = Test.get(self.get_file_operator(), name, hardware, base)
  File "semi-ate\src\ate_projectdatabase\ate_projectdatabase\Test.py", line 11, in get
    .one()
  File "semi-ate\src\ate_projectdatabase\ate_projectdatabase\FileOperator.py", line 172, in one
    assert (len(items) == 1), f'{len(items)}'
AssertionError: 0

**Comment by Zlin526F** [comment]
What is the purpose of this 'remove'? 
- If a test occurs in multiple groups, should it remove the test from that group?
- Or should the test be deleted from all groups?
