### ISSUE TITLE
An exception occurs when calling Compile Pattern the second time

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#318]
![image](https://user-images.githubusercontent.com/75318923/225865401-18e1f491-9120-41e2-b411-48a7856610b5.png)

Traceback (most recent call last):
  File "c:\users\jung\ate\packages\envs\299-add-tester-gui\semi-ate\src\ate_spyder\ate_spyder_stil\plugin.py", line 168, in compile_patterns
    self.get_container().compile_stil(patterns, sig_to_chan_path)
  File "c:\users\jung\ate\packages\envs\299-add-tester-gui\semi-ate\src\ate_spyder\ate_spyder_stil\widgets\main_widget.py", line 364, in compile_stil
    self.output_tree.append_file_msg(tree_msg)
  File "c:\users\jung\ate\packages\envs\299-add-tester-gui\semi-ate\src\ate_spyder\ate_spyder_stil\widgets\main_widget.py", line 203, in append_file_msg
    kind_node.increase_num_messages()
  File "c:\users\jung\ate\packages\envs\299-add-tester-gui\semi-ate\src\ate_spyder\ate_spyder_stil\widgets\main_widget.py", line 101, in increase_num_messages
    self.setText(0, title)
RuntimeError: wrapped C/C++ object of type CategoryItem has been deleted

**Comment by Zlin526F** [comment]
fix it with:
change src\ate_spyder\ate_spyder\widgets\main_widget.py:
               316         self.output_tree.clear()  ->     self.output_tree.clear_results() 

This is fixed in branch https://github.com/Semi-ATE/Semi-ATE/tree/299-add-tester-gui_1
