### ISSUE TITLE
AssertionError when you close a project and open another project with different target

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#327]
![image](https://github.com/Semi-ATE/Semi-ATE/assets/75318923/bd502a97-4c9f-4eef-a33f-5c320ea897bb)

  File "c:\users\xxxx\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_projectdatabase\ate_projectdatabase\Device.py", line 9, in get
    return session.query(Types.Device())\
  File "c:\users\xxxx\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_projectdatabase\ate_projectdatabase\FileOperator.py", line 172, in one
    assert (len(items) == 1), f'{len(items)}'
AssertionError: 0
TreeModel.py _update(<ate_spyder.widgets.actions_on.tests.TestItems.TestItemChild.TestItemChildTarget object at 0x000001CC83B8D790>, HW0, FT, Device1             
TreeModel.py _reset_flows Device1
Traceback (most recent call last):
  File "c:\users\xxxx\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\model\TreeModel.py", line 81, in <lambda>
    self.itemChanged.connect(lambda item: self._update(item, self.hardware, self.base, self.target))
  File "c:\users\xxxx\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\model\TreeModel.py", line 266, in _update
    self.update(hw, base, target)

**Comment by Zlin526F** [comment]
The problem is that, when switching projects, the signals are still triggered using the old project parameters before the new values have been fully initialised. 

In TreeModel.py Zeile 81: self.itemChanged.connect(lambda item: self._update(item, self.hardware, self.base, self.target))

-> The lambda captures `self.hardware`, `self.base` and `self.target` at the time of invocation, not at the time the signal is raised. When switching projects, this results in queries with invalid values.

**Comment by Zlin526F** [comment]
The branch  https://github.com/Semi-ATE/Semi-ATE/tree/refs/heads/327-assertionerror-close-and-open-another-project   should solve this problem.

**Comment by Zlin526F** [comment]
The branch is now in the master, it should be solved this problem.
