### ISSUE TITLE
exception occurs when you open the excel test list import a second time with a different assignment

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Semi-ATE#335]
I think the cause is the mappingATEDic, this will not reset.
___________________________________________________________________________
Traceback (most recent call last):
  File "C:\Users\jung\maxiconda\envs\Semi-ATE_5.4.3_python3.9\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Unnamed: 1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\utils\ExceptionHandler.py", line 21, in handle_exceptions
    call_back_function()
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\TestItem.py", line 109, in <lambda>
    lambda: excel_test_dialog(self.project_info, selected_file),
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 823, in excel_test_dialog
    newTestWizard = ExcelTestWizard(project_info, selected_file)
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 117, in __init__
    self.create_excel_table(filename)
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 202, in create_excel_table
    self.verify()
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 452, in verify
    table_name = self.workpage[self.get_dicKey(mappingATEDic, 'name')]
  File "C:\Users\jung\maxiconda\envs\Semi-ATE_5.4.3_python3.9\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\jung\maxiconda\envs\Semi-ATE_5.4.3_python3.9\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'Unnamed: 1'
Traceback (most recent call last):
  File "C:\Users\jung\maxiconda\envs\Semi-ATE_5.4.3_python3.9\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Unnamed: 1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\utils\ExceptionHandler.py", line 21, in handle_exceptions
    call_back_function()
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\TestItem.py", line 109, in <lambda>
    lambda: excel_test_dialog(self.project_info, selected_file),
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 823, in excel_test_dialog
    newTestWizard = ExcelTestWizard(project_info, selected_file)
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 117, in __init__
    self.create_excel_table(filename)
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 202, in create_excel_table
    self.verify()
  File "c:\users\jung\ate\packages\envs\semi-ate-5.4.3\semi-ate\src\ate_spyder\ate_spyder\widgets\actions_on\tests\ExcelTestWizard.py", line 452, in verify
    table_name = self.workpage[self.get_dicKey(mappingATEDic, 'name')]
  File "C:\Users\jung\maxiconda\envs\Semi-ATE_5.4.3_python3.9\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\jung\maxiconda\envs\Semi-ATE_5.4.3_python3.9\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'Unnamed: 1'

**Comment by Zlin526F** [comment]
There are some other bugs in this widget:
- If you cancel the wizard, the Excel file remains open and cannot be written to by another programme.
- output.mpr get errors
- The Description is displayed as a single character on each line
<img width="455" height="411" alt="Image" src="https://github.com/user-attachments/assets/50af46b5-5707-4420-8f57-994da7a33ebe" />

**Comment by Zlin526F** [comment]
should be fixed in https://github.com/Semi-ATE/Semi-ATE/tree/335-excel-test-list-import_3
